COMP-001
albert-yim/tanyak-laundry pull request #5
Opened 2024-08-16 14:05 UTC by Charlie0921

Basic Button Components
- Added on login page
- Functionality test available with console.log
- Font style has not yet been added

2024-08-16 14:20 UTC, albert-yim requested changes
화이팅하자..

2024-08-16 14:20 UTC, albert-yim commented on .gitignore
> +>>>>>>> PAGE-001
이부분 다시 수정 부탁해

2024-08-16 14:20 UTC, albert-yim commented on package.json
> +    "react-router-dom": "^6.26.1",
이거 그냥 냅두고 담부터는 package 버전 바뀌면 다시 체크하고 pull-request 올려
pull-request 올리고 너도 한번 변경사항 쭉 체크하고 이상하다 싶은건 바로 수정해서 다시 push 해야해

2024-08-16 14:20 UTC, albert-yim commented on src/components/BasicButton/BasicButton.scss
> +  src: url("https://replit.com/@KunjoongKim/tanyak-laundry#src/assets/fonts/NanumSquareRoundB.ttf") format("truetype");
경로는 전체경로로 하면 안되고 너 로컬에 의존하면 안돼 
상대경로로하던 /src/assets 이렇게 시작
상대경로면 ../assets 이렇게려나? 무튼 하고 체크해봐

2024-08-16 14:20 UTC, albert-yim commented on src/components/BasicButton/BasicButton.tsx
> +  onClick?: any;
type 웬만한 경우에서 절대 any를 쓰면 안돼 onClick은 react 기본 handler중 하나야 
onClick은 MouseEventHandler
그리고 버튼 onClick에 왜 ? 달았어? (? 단 이유 댓글로 남겨줘)

2024-08-16 14:20 UTC, albert-yim commented on src/components/BasicButton/BasicButton.tsx
> +}
interface를 쓴 이유가 있을까? (이것도 댓글로 이유 남겨줘)

2024-08-16 14:20 UTC, albert-yim commented on src/components/BasicButton/BasicButton.tsx
> +function BasicButton({ name, onClick }: ButtonProps) {
위에 interface의 큰 이유가 없다면 웬만하면 type으로 다 해결 돼 typescript가 뭔지 좀 더 기본 개념에 대해 시간 될때 유튭이라도 보면 도움 될거야

무튼 이 경우도 type 명시 위에서 해줬으니 function BasicButton({ name, onClick }: ButtonTypes) { 
이렇게 해도 돼

2024-08-16 14:20 UTC, albert-yim commented on src/components/BasicButton/BasicButton.tsx
> +function BasicButton({ name, onClick }: ButtonProps) {
추가적으로 name도 이렇게 사용하면 너무 고정적이라 <BasicButton> 로그인 </BasicButton> 이렇게 못쓰잖아? 
이렇게 쓰면 저 안에 쓰는걸 우리는 children으로 쓴단 말이지? 
그래서 type에 children을 추가해주고 (type은 ReactNode)
{name} 대신 {children} 써주자

2024-08-16 14:20 UTC, albert-yim commented on src/components/BasicButton/BasicButton.tsx
> +      {name}
위에 comment 남긴거처럼 {children}

2024-08-16 15:13 UTC, Charlie0921 commented on src/components/BasicButton/BasicButton.tsx
> +  onClick?: any;
[](https://velog.io/@uuuuooii/%EC%9E%AC%EC%82%AC%EC%9A%A9-%EA%B0%80%EB%8A%A5%ED%95%9C-%EB%B2%84%ED%8A%BC-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EB%A7%8C%EB%93%A4%EA%B8%B0-TypeScript-Emotion)

2024-08-16 15:15 UTC, Charlie0921 commented on src/components/BasicButton/BasicButton.tsx
> +  onClick?: any;
타입스크립트 컴포넌트는 처음이라 문서를 참고해서 버튼을 만들어보았는데 다음부터는 무작정 따라하기보다는 이해하고 진행하도록 하겠습니다

[타입스크립트 버튼 컴포넌트](https://velog.io/@uuuuooii/%EC%9E%AC%EC%82%AC%EC%9A%A9-%EA%B0%80%EB%8A%A5%ED%95%9C-%EB%B2%84%ED%8A%BC-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EB%A7%8C%EB%93%A4%EA%B8%B0-TypeScript-Emotion)

2024-08-16 15:16 UTC, Charlie0921 commented on src/components/BasicButton/BasicButton.tsx
> +}
이것도 위와 같이 문서를 참고해서 만들었습니다;;

2024-08-23 14:04 UTC, Charlie0921 commented on package.json
> +    "react-router-dom": "^6.26.1",
버전확인 완료했습니다

2024-08-23 14:04 UTC, Charlie0921 commented on src/components/BasicButton/BasicButton.scss
> +  src: url("https://replit.com/@KunjoongKim/tanyak-laundry#src/assets/fonts/NanumSquareRoundB.ttf") format("truetype");
폰트는 일단 스킵하는 걸로 진행하였습니다

2024-08-23 14:05 UTC, Charlie0921 commented on src/components/BasicButton/BasicButton.tsx
> +  onClick?: any;
`export type ButtonTypes = {
  onClick: () => void;
  children: ReactNode;
};`

로 수정 완료했습니다

2024-08-23 14:06 UTC, Charlie0921 commented on src/components/BasicButton/BasicButton.tsx
> +}
수정 완료했습니다

2024-08-23 14:06 UTC, Charlie0921 commented on src/components/BasicButton/BasicButton.tsx
> +function BasicButton({ name, onClick }: ButtonProps) {
`function BasicButton({ children, onClick }: ButtonTypes) {`
수정 완료했습니다

2024-08-23 14:06 UTC, Charlie0921 commented on src/components/BasicButton/BasicButton.tsx
> +      {name}
수정 완료했습니다

2024-08-23 14:57 UTC, albert-yim reviewed
마이너한 의견 공유

2024-08-23 14:57 UTC, albert-yim commented on src/pages/Login/Login.tsx
> +  );
원상복귀 하세요

2024-08-23 14:57 UTC, albert-yim commented on src/components/BasicButton/BasicButton.tsx
> +import "./BasicButton.scss";
module.scss 로 변경 부탁드려요

2024-08-24 14:01 UTC, albert-yim approved these changes
Good!

2024-08-24 14:01 UTC, merged